# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Corsair.iCUE.5
PackageVersion: 5.21.107
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --quiet
  SilentWithProgress: --quiet
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://www3.corsair.com/software/CUE_V5/public/modules/windows/installer/Install%20iCUE.exe
  InstallerSha256: 5213B2BD8AC3D2B4D28F19FBBB9BFC994A22EC168C7E8ED8CC820A71F64683B2
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-11-20
