# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: VirtualGL.VirtualGL
PackageVersion: 3.1.1
PackageLocale: en-US
Publisher: The VirtualGL Project
PublisherUrl: https://virtualgl.org/
PublisherSupportUrl: https://github.com/VirtualGL/virtualgl/issues
Author: The VirtualGL Project
PackageName: VirtualGL-Utils
PackageUrl: https://github.com/VirtualGL/virtualgl
License: wxWindows Library Licence
LicenseUrl: https://github.com/VirtualGL/virtualgl/raw/main/LICENSE.txt
Copyright: Copyright (C) 1998-2005 Julian Smart, Robert Roebling et al
CopyrightUrl: https://github.com/VirtualGL/virtualgl/raw/main/LICENSE.txt
ShortDescription: 3D Without Boundaries
Description: VirtualGL redirects 3D commands from a Unix/Linux OpenGL application onto a server-side GPU and converts the rendered 3D images into a video stream with which remote clients can interact to view and control the 3D application in real time.
Tags: []
ReleaseNotesUrl: https://github.com/VirtualGL/virtualgl/releases/tag/3.1.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/VirtualGL/virtualgl/wiki
ManifestType: defaultLocale
ManifestVersion: 1.6.0
